### PR TITLE
Add support for *nixes operating systems.

### PR DESCRIPTION
**Pull request by johalun**
rustfmt might have reformatted the code a bit automatically..

### CODE REVIEW

**Comment by daschl** [comment]
Thanks much for your contribution 👍I'll take a closer look soon but on a first glance It looks great

**Comment by daschl** [comment]
@johalun looks good to me, can you please squash it into one commit? then its ready to go in . thanks!

**Comment by johalun** [comment]
Done!  Thanks for making this crate! :)

**Comment by johalun** [comment]
Can we make a new release with this PR? Thanks!

**Comment by daschl** [comment]
@johalun sure :)

**Comment by daschl** [comment]
@johalun released 0.5! please let me know if you have any problems - thanks much again for contributing

**Comment by johalun** [comment]
Great! Thanks! I've seen that hwloc 1.11.6 is out. Do you have an ETA for a release to match?

**Comment by daschl** [comment]
I think you can already use it, unless they broke some API. our binding hasn't really changed on a version by version basis, I just put in the README what I tested. If something breaks let me know and we can work it out.

**Comment by johalun** [comment]
cargo test had no problems with 1.11.6 and the newly released 1.11.7 :)  Seems 1.11.7 was mostly fixes to the apps and not the library.

**Pull request merged**
